spring:
  datasource:
    url: jdbc:sqlite:meta.db

  jackson:
    generator:
      write-numbers-as-strings: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl