### 新建菜单
POST http://localhost:8080/storage/tAppMenu/
Content-Type: application/json

{
  "name": "数据视角",
  "userFriendlyName": {
    "zh_CN": "数据视角"
  },
  "description": {
    "zh_CN": "数据视角"
  },
  "icon": "",
  "path": "/data",
  "parentId": 0
}

### 删除菜单
DELETE http://localhost:8080/storage/tAppMenu/
Content-Type: application/json

{
  "id":"-653946878"
}

### 查询菜单
GET http://localhost:8080/storage/tAppMenu/item/1

### 列出菜单
GET http://localhost:8080/storage/tAppMenu

### 第一层菜单
GET http://localhost:8080/storage/tAppMenu/firstLevel

### 获取子菜单
GET http://localhost:8080/storage/tAppMenu/1/subMenus
